http:
  routers:
    frontend:
      rule: "Host(`app.localhost`)"
      service: frontend-svc
      entryPoints:
        - web

    shorten:
      rule: "Host(`api.localhost`) && PathPrefix(`/shorten`)"
      service: shorten-svc
      entryPoints:
        - web
      middlewares:
        - corsHeader

    forward:
      rule: "Host(`localhost`) && PathRegexp(`^/(.+)$`)"
      service: forward-svc
      entryPoints:
        - web
      middlewares:
        - corsHeader

  middlewares:
    corsHeader:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginListRegex:
          - "^http://localhost(:[0-9]+)?$"
        addVaryHeader: true

  services:
    shorten-svc:
      loadBalancer:
        servers:
          - url: "http://shortening-service:3000"

    forward-svc:
      loadBalancer:
        servers:
          - url: "http://forwarding-service:3000"

    frontend-svc:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
