http:
  routers:
    shorten:
      rule: "Host(`murl.pw`) && PathPrefix(`/shorten`)"
      service: shorten-svc
      entryPoints:
        - web
      middlewares:
        - corsHeader
      priority: 100

    forward:
      rule: "Host(`murl.pw`) && PathRegexp(`^/[A-Za-z0-9_-]+$`)"
      service: forward-svc
      entryPoints:
        - web
      middlewares:
        - corsHeader
      priority: 90

    frontend:
      rule: "Host(`murl.pw`)"
      service: frontend-svc
      entryPoints:
        - web
      priority: 10

  middlewares:
    corsHeader:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginListRegex:
          - "^https?://murl\\.pw$"
        addVaryHeader: true

  services:
    shorten-svc:
      loadBalancer:
        servers:
          - url: "http://shortening-service:3000"

    forward-svc:
      loadBalancer:
        servers:
          - url: "http://forwarding-service:3000"

    frontend-svc:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
