FROM oven/bun:latest AS build
WORKDIR /app

ARG VITE_API_BASE_URL=https://murl.pw

COPY packages/frontend/package.json ./package.json

RUN bun install --no-check

COPY packages/frontend/ ./

# expose API base URL to Vite build
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN bun run build

FROM nginx:1.29.1-alpine AS release

COPY infra/docker/frontend-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
