FROM oven/bun:latest AS build
WORKDIR /app

ARG VITE_API_BASE_URL=http://localhost

COPY . .

RUN bun install --no-check

WORKDIR /app/packages/frontend

# expose API base URL to Vite build
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN bun run build

FROM nginx:1.29.1-alpine AS release

COPY infra/docker/frontend-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/packages/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
